/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/Shared/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/Shared/BaseCard.vue')['default']
    BaseSnackbar: typeof import('./src/components/Shared/BaseSnackbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepCodeValidation: typeof import('./src/components/Steps/StepCodeValidation.vue')['default']
    StepConfirmData: typeof import('./src/components/Steps/StepConfirmData.vue')['default']
    StepCpf: typeof import('./src/components/Steps/StepCpf.vue')['default']
    StepDate: typeof import('./src/components/Steps/StepDate.vue')['default']
    StepSuccess: typeof import('./src/components/Steps/StepSuccess.vue')['default']
    StepValue: typeof import('./src/components/Steps/StepValue.vue')['default']
    StepWelcome: typeof import('./src/components/Steps/StepWelcome.vue')['default']
  }
}
