/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/admin/colaborador': RouteRecordInfo<'/admin/colaborador', '/admin/colaborador', Record<never, never>, Record<never, never>>,
    '/admin/colaboradorForm': RouteRecordInfo<'/admin/colaboradorForm', '/admin/colaboradorForm', Record<never, never>, Record<never, never>>,
    '/admin/solicitacoes': RouteRecordInfo<'/admin/solicitacoes', '/admin/solicitacoes', Record<never, never>, Record<never, never>>,
    '/admin/solicitacoesValidar': RouteRecordInfo<'/admin/solicitacoesValidar', '/admin/solicitacoesValidar', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/totem/': RouteRecordInfo<'/totem/', '/totem', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/admin/colaborador.vue': {
      routes: '/admin/colaborador'
      views: never
    }
    'src/pages/admin/colaboradorForm.vue': {
      routes: '/admin/colaboradorForm'
      views: never
    }
    'src/pages/admin/solicitacoes.vue': {
      routes: '/admin/solicitacoes'
      views: never
    }
    'src/pages/admin/solicitacoesValidar.vue': {
      routes: '/admin/solicitacoesValidar'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/totem/index.vue': {
      routes: '/totem/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
